name: Check gpt-macro
on: [pull_request]

env:
  RUSTFLAGS: -D warnings

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rust-src clippy rustfmt
      - run: cargo clippy --all-features
      - run: cargo fmt --all -- --check
